# Generated by Django 4.2.1 on 2023-05-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_customer_state_alter_orderplaced_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerzonefrontpage',
            name='mobileName',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Uttarakhand', 'Uttarakhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Puducherry', 'Puducherry'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('On the Way', 'On the Way'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='mobileCategory',
            field=models.CharField(choices=[('iphone', 'iphone'), ('samsung', 'samsung'), ('poco', 'poco'), ('realme', 'realme'), ('redmi', 'redmi')], max_length=10),
        ),
    ]
